package com.che.dao;

import com.che.pojo.po.CapRole;
import com.che.pojo.po.CapRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CapRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    long countByExample(CapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    @Delete({
        "delete from CAP_ROLE",
        "where ROLE_ID = #{roleId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    @Insert({
        "insert into CAP_ROLE (ROLE_ID, ROLE_CODE, ",
        "ROLE_NAME, ROLE_DESC, ",
        "CREATEUSER, CREATETIME)",
        "values (#{roleId,jdbcType=VARCHAR}, #{roleCode,jdbcType=VARCHAR}, ",
        "#{roleName,jdbcType=VARCHAR}, #{roleDesc,jdbcType=VARCHAR}, ",
        "#{createuser,jdbcType=DECIMAL}, #{createtime,jdbcType=DATE})"
    })
    int insert(CapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    int insertSelective(CapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    List<CapRole> selectByExample(CapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_DESC, CREATEUSER, CREATETIME",
        "from CAP_ROLE",
        "where ROLE_ID = #{roleId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.che.dao.CapRoleMapper.BaseResultMap")
    CapRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAP_ROLE
     *
     * @mbg.generated
     */
    @Update({
        "update CAP_ROLE",
        "set ROLE_CODE = #{roleCode,jdbcType=VARCHAR},",
          "ROLE_NAME = #{roleName,jdbcType=VARCHAR},",
          "ROLE_DESC = #{roleDesc,jdbcType=VARCHAR},",
          "CREATEUSER = #{createuser,jdbcType=DECIMAL},",
          "CREATETIME = #{createtime,jdbcType=DATE}",
        "where ROLE_ID = #{roleId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CapRole record);
}