server: 
  port: 8081

spring:
  redis:
    host: rebey.cn #换成你的redis服务器地址
    port: 6379 #端口（默认）
    password: 123456 #000000无效
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 80
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 80
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  